import type { Metadata } from "next";
import { Italianno, Italiana, Inter } from "next/font/google";
import "./globals.css";

const italianno = Italianno({
  variable: "--font-italianno",
  weight: "400", // Italianno cuma punya 1 weight
  subsets: ["latin"],
});

const italiana = Italiana({
  variable: "--font-italiana",
  weight: "400", // Italiana juga cuma 400
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Simple Dark - Wedding Theme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${italianno.variable} ${italiana.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
